### ISSUE TITLE
Median of two sorted arrays of same size(Java Program)

### ISSUE THREAD

**Issue by ManavArora26** [Rjndrkha/Data-Structure_Code-Program_CLOSED#308]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

 

Example 1:

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000
Explanation: merged array = [1,2,3] and median is 2.
Example 2:

Input: nums1 = [1,2], nums2 = [3,4]
Output: 2.50000
Explanation: merged array = [1,2,3,4] and median is (2 + 3) / 2 = 2.5.
 

Constraints:

nums1.length == m
nums2.length == n
0 <= m <= 1000
0 <= n <= 1000
1 <= m + n <= 2000
-106 <= nums1[i], nums2[i] <= 106

**Comment by SKSilentKiller** [comment]
Can I work on this? @ManavArora26

**Comment by Aditi192002** [comment]
Please assign me this issue.

**Comment by abhijeet-crypto** [comment]
i want to work on this

**Comment by PawangRai** [comment]
Please assign this issue to me

**Comment by Teju-1212** [comment]
I know this problem

**Comment by aniketkumar-1907** [comment]
Can I work on this problem I have done it before @ManavArora26 ?
