### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by RidhikaJoshi** [Rjndrkha/Data-Structure_Code-Program_CLOSED#330]
Trapping Rain Water in Cpp

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by yesdhruv** [comment]
Hey @Rjndrkha I would like to work on this problem , I have expertise in DSA and problem solving

**Comment by croquis** [comment]
Please assign me this issue

**Comment by manav0702** [comment]
Please can I work on this

**Comment by aniketkumar-1907** [comment]
Can I work on this issue I think I have the solution you might need ?
