### ISSUE TITLE
A C++ Implementation of Trie Data Structure

### ISSUE THREAD

**Issue by Rahul-Roy-21** [Rjndrkha/Data-Structure_Code-Program_CLOSED#492]
Hi @Rjndrkha, I wish to add a trie.cpp with basic functionalities like Search, Insert, Delete.. Please assign me to this task and add the 'hacktoberfest-accepted' label to this issue.

**Comment by rohitpadage** [comment]
I have a good grasp over trie data structure. i'm ready to implement in c++. 
Please assign.
