### ISSUE TITLE
Will add the Java program to convert Roman Numbers to Integers.

### ISSUE THREAD

**Issue by Anubhavgupta14** [Rjndrkha/Data-Structure_Code-Program_CLOSED#506]
Will add the Java program to convert Roman Numbers to Integers.
(Tested in LeetCode)
@Rjndrkha Kindly assigned it to me.

**Comment by malikzi21** [comment]
Will add the cpp program to convert Roman Numbers to Integers please assign this task to me

**Comment by SJ-Kumar** [comment]
I would like to add my java code here. Please assign this to me.

**Comment by manav0702** [comment]
Please assign this to me

**Comment by Gauravshah001** [comment]
Plz assign this issue to me.
