### ISSUE TITLE
Detect Loop in Linked List((Floyd's Cycle Detection Algorithm)

### ISSUE THREAD

**Issue by Spardha-hash** [Rjndrkha/Data-Structure_Code-Program_CLOSED#539]
Please assign this issue to me.

**Comment by yesdhruv** [comment]
Hey ! @Rjndrkha, I would like to work on this problem as I have expertise in DSA , I will  include comments for clear understanding of code  and then discuss it's Time and space complexity.

Thanks !

**Comment by vallabhiaf** [comment]
Hey looking forward to implement this in python

**Comment by croquis** [comment]
Please assign me this issue
