### ISSUE TITLE
Food Delivery System

### ISSUE THREAD

**Issue by mrsaif7631** [Rjndrkha/Data-Structure_Code-Program_CLOSED#586]
Contribution to hacktober fest 2022,

**Comment by 22tanyabansal** [comment]
hey @Rjndrkha Please assign this task to me. I want to contribute on hacktoberfest 2022

**Comment by kuldeep-gaur** [comment]
Hello sir can you assign this issue to me?

**Comment by amit05sept** [comment]
hello sir, please assign this task to me, I will make this website responsive.

**Comment by ARSLAN7861** [comment]
Can I have this project? you wont regret giving me this
