### ISSUE TITLE
Ping Pong

### ISSUE THREAD

**Issue by SarthakSharma660** [Rjndrkha/Data-Structure_Code-Program_CLOSED#620]
Ping Pong using python, a beginner-friendly project. This game will help you to learn the basic concepts of OOPs.

**Comment by vallabhiaf** [comment]
Hello can i try to implement this

**Comment by Abhyuday0409** [comment]
Hello, can I get to implement this @SarthakSharma660?

**Comment by SarthakSharma660** [comment]
I am not the owner buddy

**Comment by Pranjal2870** [comment]
Please assign me this project

**Comment by GeeteshMehto** [comment]
Hello sir,Please assign this to me, as i already made this in past.
