### ISSUE TITLE
Search In 2D matrix

### ISSUE THREAD

**Issue by gaurdivit** [Rjndrkha/Data-Structure_Code-Program_CLOSED#720]
hello, Divit this side
I really want to contribute to your repository for HactoberFest
Thankyou

**Comment by Soumav-0o0** [comment]
Hello,
I would really like to contribute to your repository, can you please assign this issue to me?

**Comment by AdityaShaw1** [comment]
Hlo i would like to contribute to this issue pls assign me to this

**Comment by Krishn1412** [comment]
Hello, I would appreciate it if you could assign this issue to me.
Thanks and regards
Krishn
